- block:
  - name: "Users - creating normal users"
    user:
      name: "{{ item }}"
    with_items: "{{ role_init.users.normal }}"

  - name: "Users - creating sudo users"
    user:
      name: "{{ item }}"
      groups: wheel
      append: yes 
    with_items: "{{ role_init.users.sudo }}"

  - name: "Users - setting keys"
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '{{ role_init.users.keys_path }}/{{ item }}.pub') }}"
    with_items:
    - "{{ role_init.users.sudo }}"
    - "{{ role_init.users.normal }}"
  tags: init_users

- name: "Creating no password sudo configuration under /etc/sudoers.d"
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/{{ item }}"
    validate: "visudo -cf %s"
    owner: root
    group: root
    mode: "0440"
  with_items:
  - "{{ role_init.users.sudo }}"
  tags: init_sudo
